#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1

scp -o StrictHostKeyChecking=no -i "~/.ssh/id_rsa" "$file_path" "ubuntu"@"54.90.18.3":~/
