#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# enable a dedicated PPA with the following command: 
if ! command -v haproxy &> /dev/null
then
        apt-get install --no-install-recommends software-properties-common
        add-apt-repository ppa:vbernat/haproxy-2.9
        # install
        apt-get install -y haproxy=2.9.\*
fi

# config
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg

frontend http_frontend
    bind *:80
    mode http
    default_backend start_point

backend start_point
    balance roundrobin
    mode http
    server 512729-web-01 54.90.18.3:80 check
    server 512729-web-02 100.26.232.118:80 check
EOF

# Make sure that HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# Restart
sudo systemctl restart haproxy
