#!/usr/bin/env bash
#  Nginx likes port 80 
if ! grep -q 'listen 80' /etc/nginx/sites-enabled/default; then
    sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
    sudo service nginx restart
fi

