#!/usr/bin/env bash
#task 4

count=1
while [ $count -le 10 ]
do

        if [ $count == 9 ]
        then
                echo "Best School"
                echo "hi"
        else
                echo "Best School"
        fi
        ((count++))
done