#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ip_addresses=$(ifconfig | grep 'inet ' | awk '{print $2}')
for ip in $ip_addresses; do
  echo "$ip"
done